# Generated by Django 4.0.3 on 2022-06-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nested_sub_cate',
        ),
        migrations.DeleteModel(
            name='NestedSubCategory',
        ),
    ]
